apiVersion: v1
kind: Service
metadata:
  name: cloud-dashboard-service
spec:
  selector:
    app: cloud-dashboard
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080